swagger: "2.0"
info:
  version: 1.0.0
  title: "Esame12B-178798"
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: federico.demartin@studenti.unitn.it
    url: https://esame12b-178798.herokuapp.com/
  license:
    name: MIT
    url: https://esame12b-178798.herokuapp.com/
host: esame12b-178798.herokuapp.com
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /getAstronauti:
    get:
      description: |
       restituisce tutta la lista degli astronauti
      operationId: findPets
      responses:
        200:
          description: lista astronauti
          schema:
            type: array
            items:
              $ref: '#/definitions/Astronauta'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /addAstronauta:  
    post:
      description: crea un nuovo astronauta
      operationId: addAstronauta
      parameters:
         - in: body
           name: Astronauta
           description: astronauta da aggiungere
           schema:
            type: object
            required:
              - fistname
              - lastname
              - isInSpace
            properties:
              fistname:
                type: string
              lastname:
                type: string
              isInSpace:
                type: string
      responses:
        200:
          description: Astronauta response
          schema:
            $ref: '#/definitions/Astronauta'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /getAstronauti/{id}:
    get:
      description: Ritorna austronauta avente id inserito
      operationId: trova astronauta in base id
      parameters:
        - name: id
          in: path
          description: ID astronauta
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Astronauta response
          schema:
            $ref: '#/definitions/Astronauta'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /modificaAs/{id}:
    put:
      description: modifica l'austronauta richiesto tramite id
      operationId: modifica astronauta in base id
      parameters:
        - name: id
          in: path
          description: ID astronauta
          required: true
          type: integer
          format: int64
        - in: body
          name: Astronauta
          description: astronauta da modificare
          schema:
            type: object
            properties:
              fistname:
                type: string
              lastname:
                type: string
              isInSpace:
                type: string
      responses:
        200:
          description: Astronauta modificato con successo
          schema:
            $ref: '#/definitions/Astronauta'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
        
        
    
definitions:
  Astronauta:
    allOf:
      - $ref: '#/definitions/NewAstronauta'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  NewAstronauta:
    required:
      - firstname
      - lastname
      - isInSpace
    properties:
      name:
        type: string
      tag:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string